Add event to p_locale_xhtml()
splitbrain/dokuwiki pull request #3579
Opened 2022-01-05 15:24 UTC by annda

Allows plugins to modify localized text

2022-01-05 16:33 UTC, splitbrain requested changes
Currently the event handler has no way of knowing which locale is being shown. The `$id` should be passed with the event data.

2022-01-05 16:45 UTC, annda commented
The `$id` is now included.

2022-01-06 08:39 UTC, splitbrain commented on inc/parserutils.php
>      return $html;
You return the original $html instead of the HTML modified by the plugin.

2022-01-06 08:41 UTC, splitbrain commented on inc/parserutils.php
>      return $html;
I also wonder if the event shouldn't wrap around `p_cached_output(localeFN())` so plugins can also change the `$id` in the `BEFORE` event?

2022-01-10 10:52 UTC, merged

2022-01-10 10:52 UTC, splitbrain commented
@annda Can you update the docs please?