Add event to modify text in denied action
splitbrain/dokuwiki pull request #3580
Opened 2022-01-05 15:34 UTC by annda

Let plugins suppress/replace the text displayed on the denied page.

The event is very simple and it does not handle the text and the login form separately.

2022-01-05 16:35 UTC, splitbrain requested changes
This would currently allow a plugin to supress *all* output of the denied action with no way to add new output. Seems not very useful.

For the intended purpose it would make more sense if this plugin would only supress the UI\Login->show() call, not all output.

2022-01-05 16:41 UTC, annda commented
A plugin can still `echo` text and it will be displayed instead of the default.

@splitbrain Should I still change the behavior?

2022-01-06 08:36 UTC, splitbrain commented
When plugins modify content, it should be through the event data so chained plugins have a chance to see what the previous plugin did. But yeah for this, I believe it would be fine to be able to simply suppress the form.

2022-01-10 10:49 UTC, merged

2022-01-10 10:49 UTC, splitbrain commented
@annda can you add the documentation please?