translate the logviewer plugin into French
splitbrain/dokuwiki pull request #3792
Opened 2022-10-09 17:34 UTC by schplurtz

These are French texts for the logviewer plugin.

kind of workaround  for #3791 ;-)

2022-10-09 18:50 UTC, trebmuh requested changes

2022-10-09 18:50 UTC, trebmuh commented on lib/plugins/logviewer/lang/fr/intro.txt
> +ou de les inclure dans un rapport de bug.
bug -> bogue

2022-10-09 18:50 UTC, trebmuh commented on lib/plugins/logviewer/lang/fr/lang.php
> +$lang['js']['filter'] = 'Filter les lignes:';
Filter -> Filtrer

2022-10-10 04:57 UTC, schplurtz commented on lib/plugins/logviewer/lang/fr/intro.txt
> +ou de les inclure dans un rapport de bug.
Non, je ne ferai pas ça. Si bogue a été un temps une suggestion de traduction valable, c'est un terme qui n'est plus du tout utilisé dans le langage courant. Ainsi dit-on le bug de l'an 2000 ou le bogue de l'2000 ? Dans la langue orale, on dit "Il a bugué" (orthographe ?) en parlant d'une personne qui s'est trompée, n'a pas su se décider, s'est trouvée dépassée par les évènements. Voir aussi https://books.google.com/ngrams/graph?content=bug%2Cbogue&year_start=1800&year_end=2019&corpus=30&smoothing=3

2022-10-10 04:58 UTC, schplurtz commented on lib/plugins/logviewer/lang/fr/lang.php
> +$lang['js']['filter'] = 'Filter les lignes:';
oui, merci. J'ajoute un commit immédiatement.

2022-10-10 05:23 UTC, trebmuh commented on lib/plugins/logviewer/lang/fr/intro.txt
> +ou de les inclure dans un rapport de bug.
C'est pourtant un mot qui existe dans les dictionnaires :

- https://www.le-dictionnaire.com/definition/bogue
- https://dictionnaire.lerobert.com/definition/bogue
- https://www.larousse.fr/dictionnaires/francais/bogue/10005

et qui est recommandé par par la langue française : https://www.culture.fr/franceterme/result?francetermeSearchTerme=bug&francetermeSearchDomaine=0&francetermeSearchSubmit=rechercher&action=search

PS : dans la langue orale, personne ne dit "il a bugué", mais "il a beugué"

2022-10-10 06:12 UTC, merged